version: '3'
services:
  express-server:
    image: aleksandrskondratjevs/prerender:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - XDG_RUNTIME_DIR=/tmp/runtime
    depends_on:
      - mongo
    network_mode: host

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dA8YCJycG64OGDo

  redis-stack:
      image: redis/redis-stack:latest
      ports:
        - "6379:6379"
        - "8001:8001"
      volumes:
        - redis-data:/data

volumes:
  redis-data: